spring.application.name=coreconnectmessagingplatform
spring.datasource.url=jdbc:postgresql://localhost:5432/dyashin_messaging
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#JWT secret value
jwt.secret= Y29yZWNvbm5lY3Rfc2VjcmV0X2tleV8xMjM0NTY3ODkwMTIzNDU2Nzg5MA==
jwt.expiration=86400000  



